"""empty message

Revision ID: 2548e747322f
Revises: e5bdb234a558
Create Date: 2021-02-17 13:49:32.672347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2548e747322f'
down_revision = 'e5bdb234a558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tutors_about_key', 'tutors', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tutors_about_key', 'tutors', ['about'])
    # ### end Alembic commands ###
