"""empty message

Revision ID: 2dbfaedf50e9
Revises: 5c91a836addb
Create Date: 2021-02-17 22:19:33.766152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbfaedf50e9'
down_revision = '5c91a836addb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('day', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'day')
    # ### end Alembic commands ###
