"""empty message

Revision ID: 5c91a836addb
Revises: 2548e747322f
Create Date: 2021-02-17 22:16:13.504010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c91a836addb'
down_revision = '2548e747322f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('time', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'time')
    # ### end Alembic commands ###
